global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    static_configs:
    - targets: ["monitoring_node_exporter:9100"]
